version: "3.5"

services: 
  front:
    build:
      context: .
      dockerfile: ./edtech_platform_frontend/Dockerfile
    volumes:
      - ./edtech_platform_frontend/src:/var/app/src
      - ./edtech_platform_frontend/public:/var/app/public
    ports: 
      - 3000:3000
  
  back:
    build: 
      context: .
      dockerfile: ./edtech_platform/Dockerfile
    volumes:
      - ./edtech_platform:/var/app/edtech_platform
    ports: 
      - 8000:8000
    depends_on: 
      - redis_service
  
  redis_service:
    build: 
      context: .
      dockerfile: ./redis/Dockerfile
    ports: 
      - 6379:6379