# Generated by Django 3.2.4 on 2021-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
